/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-01 18:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>My Website</title>\r\n");
      out.write("    <style>\r\n");
      out.write("     /* 이전/다음 버튼 스타일 */\r\n");
      out.write("        .pagination {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .pagination a {\r\n");
      out.write("            color: black;\r\n");
      out.write("            float: center;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: background-color .3s;\r\n");
      out.write("        }\r\n");
      out.write("        .pagination a.active {\r\n");
      out.write("            background-color: #007BFF;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .pagination a:hover:not(.active) {\r\n");
      out.write("            background-color: #ddd;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        nav {\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        nav ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        nav li {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin: 5px;\r\n");
      out.write("            background-color: #777;\r\n");
      out.write("            padding: 5px 15px;\r\n");
      out.write("        }\r\n");
      out.write("        nav a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        nav a:hover {\r\n");
      out.write("            background-color: #888;\r\n");
      out.write("        }\r\n");
      out.write("        section {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        /* 게시판 테이블 스타일 */\r\n");
      out.write("        table {\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        td {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("        /* 검색칸 스타일 */\r\n");
      out.write("        .search-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("        }\r\n");
      out.write("        .search-container input[type=\"text\"] {\r\n");
      out.write("            width: 300px; /* 검색칸 넓이 설정 (예시로 300px 지정) */\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .search-container input[type=\"submit\"] {\r\n");
      out.write("            padding: 5px 20px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("         /* 글쓰기 버튼 스타일 */\r\n");
      out.write("           .write-button {\r\n");
      out.write("            background-color: gray;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("          .menu-bar {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: #f1f1f1;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-bar a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 5px 15px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-bar a:hover {\r\n");
      out.write("            background-color: #ddd;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>AMORA 아파트</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#community\">커뮤니티</a></li>\r\n");
      out.write("            <li><a href=\"#second-hand\">중고거래/나눔</a></li>\r\n");
      out.write("            <li><a href=\"#joint-trading\">공동구매</a></li>\r\n");
      out.write("            <li><a href=\"#promotion\">홍보</a></li>\r\n");
      out.write("            <li><a href=\"#notice\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"#my-page\">마이페이지</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("     <!-- Menu Bar -->\r\n");
      out.write("    <div class=\"menu-bar\">\r\n");
      out.write("        <a href=\"#\">홈</a>\r\n");
      out.write("        <a href=\"#\">모임</a>\r\n");
      out.write("        <a href=\"#\">일상</a>\r\n");
      out.write("        <a href=\"#\">잡담</a>\r\n");
      out.write("        <a href=\"#\">동아리</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Content Section - Community -->\r\n");
      out.write("    <section id=\"community\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("        <table border=\"1\" cellpadding=\"5\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>번호</th>\r\n");
      out.write("                <th>분류</th>\r\n");
      out.write("                <th>제목</th>\r\n");
      out.write("                <th>조회수</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>01</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>02</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>03</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>04</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>05</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>06</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>07</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>08</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>09</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>10</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>00</a></td>\r\n");
      out.write("                <td>선택</td>\r\n");
      out.write("                <td><a href=\"#\">아모라 제목없음</td>\r\n");
      out.write("                <td>00</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- 게시판에 추가로 게시물을 표시할 수 있습니다. -->\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 검색칸 -->\r\n");
      out.write("        <div class=\"search-container\">\r\n");
      out.write("            <form action=\"#\" method=\"get\"> <!-- 검색 기능을 추가할 경우 해당 form 태그의 action과 method를 설정하십시오. -->\r\n");
      out.write("                <input type=\"text\" name=\"search\" placeholder=\"검색어를 입력하세요\"> <!-- 검색칸 -->\r\n");
      out.write("                <input type=\"submit\" value=\"검색\"> <!-- 검색 버튼 -->\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 글쓰기 버튼 -->\r\n");
      out.write("        <button class=\"write-button\">글쓰기</button>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        <!-- 검색칸 -->\r\n");
      out.write("        <!-- 글쓰기 버튼 -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 페이지 이동 버튼 -->\r\n");
      out.write("        <div class=\"pagination\">\r\n");
      out.write("            <a href=\"#\">&laquo;</a>\r\n");
      out.write("            <a class=\"active\" href=\"#\">1</a>\r\n");
      out.write("            <a href=\"#\">2</a>\r\n");
      out.write("            <a href=\"#\">3</a>\r\n");
      out.write("            <a href=\"#\">4</a>\r\n");
      out.write("            <a href=\"#\">5</a>\r\n");
      out.write("            <a href=\"#\">6</a>\r\n");
      out.write("            <a href=\"#\">7</a>\r\n");
      out.write("            <a href=\"#\">8</a>\r\n");
      out.write("            <a href=\"#\">9</a>\r\n");
      out.write("            <a href=\"#\">10</a>\r\n");
      out.write("            <a href=\"#\">&raquo;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
